package(default_visibility = ["//visibility:public"])

exports_files([
    "requirements.txt",
    "LICENSE",
    "README.md",
])

# Add a filegroup that serves as a launcher for automated builds
# filegroup(
#     name = "everything",
#     srcs = [
#         "//src/logger:everything",
#         "//src/hotswap:everything",
#     ],
# )